---
title: "Project Titanic"
author: "Connor Guest"
date: "6/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
library(tidyverse)
library(ggthemes) # visualization
library(scales) # visualization
library(mice) # imputation
library(randomForest) # classification algorithm
```

```{r}
train <- read_csv("input/train.csv")
test <- read_csv("input/test.csv")

full <- bind_rows(train, test)

# glimpse(train)
```


```{r}
full$Title <- str_sub(full$Name, str_locate(full$Name, "\\,")[, 1] + 2, str_locate(full$Name, "\\.")[ , 1] - 1)

# full %>% distinct(title)
# full %>% distinct(Sex)

table(full$Sex)

table(full$Title)

# Titles with very low cell counts to be combined to "rare" level
rare_title <- c('Dona', 'Lady', 'the Countess','Capt', 'Col', 'Don', 
                'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer')

# Also reassign mlle, ms, and mme accordingly
full$Title[full$Title == 'Mlle']        <- 'Miss' 
full$Title[full$Title == 'Ms']          <- 'Miss'
full$Title[full$Title == 'Mme']         <- 'Mrs' 
full$Title[full$Title %in% rare_title]  <- 'Rare Title'

table(full$Sex, full$Title)

# Finally, grab surname from passenger name
full$Surname <- sapply(full$Name,  
                      function(x) strsplit(x, split = '[,.]')[[1]][1])

# strsplit(full$Name, split = '[,.]')[[1]][1]

# Unique Surnames
nlevels(factor(full$Surname))

```
```{r}
# more feature engineering

# create a variable for the size of the family per person

full$Fsize <- full$SibSp + full$Parch + 1

full$Family <- paste(full$Surname, full$Fsize, sep = "_")
# how many unique families are there - two ways to do this
nlevels(factor(full$Family))
n_distinct(full$Family)

# There are 928 differnt families on board. There are 875 unique surnames.

```

```{r, message=FALSE, warning=FALSE}
full$Survived <- as.factor(full$Survived)

# Use ggplot2 to visualize the relationship between family size & survival
full[1:891,] %>%
  ggplot(aes(x = Fsize, fill = Survived)) +
  geom_bar(stat = 'count', position = 'dodge') +
  scale_x_continuous(breaks=c(1:11)) +
  labs(x = 'Family Size',
       caption = 'Smaller family sizes (2-4) had higher channces of survival') +
  theme_few()
```

